#!/usr/bin/env bash
# gen-clangd.sh — generate native/castbridge/.clangd so clangd resolves the
# openscreen-fork headers and stops emitting spurious diagnostics.
#
# The castbridge sources include headers by their fork-relative path
# (cast/castbridge/…, platform/…, json/…), which only exist inside the fork
# checkout. Without these include paths clangd can't open the first header and
# falls back to bogus errors ("std::string aka int"). ninja builds fine — this
# only fixes the editor/LSP view.
#
# Run once after setup-openscreen.sh. The output is machine-specific and
# git-ignored, so nothing absolute gets committed.
set -euo pipefail

OPENSCREEN_DIR="${OPENSCREEN_DIR:-$HOME/Workspace/skill-cast/openscreen}"
OUT_DIR="${OUT_DIR:-out/Default}"
REPO_DIR="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"
CLANGD="$REPO_DIR/native/castbridge/.clangd"

[[ -d "$OPENSCREEN_DIR" ]] || {
	echo "openscreen checkout not found: $OPENSCREEN_DIR" >&2
	echo "provision it first: bash native/integration/setup-openscreen.sh" >&2
	exit 1
}

cat >"$CLANGD" <<EOF
# GENERATED by native/integration/gen-clangd.sh — do not edit, not versioned.
# Points clangd at the openscreen fork's headers so diagnostics match ninja.
CompileFlags:
  Add:
    - -std=c++17
    - -I$OPENSCREEN_DIR
    - -I$OPENSCREEN_DIR/third_party/jsoncpp/src/include
    - -I$OPENSCREEN_DIR/third_party/abseil
    - -I$OPENSCREEN_DIR/$OUT_DIR/gen
  CompilationDatabase: $OPENSCREEN_DIR/$OUT_DIR
EOF
echo "wrote $CLANGD"

# Best-effort: export a compile DB from ninja for accurate per-file defines.
NINJA="${NINJA:-$(command -v ninja || echo "$OPENSCREEN_DIR/../depot_tools/ninja")}"
if [[ -x "$NINJA" || -n "$(command -v "$NINJA" 2>/dev/null)" ]]; then
	if (cd "$OPENSCREEN_DIR" && "$NINJA" -C "$OUT_DIR" -t compdb >"$OUT_DIR/compile_commands.json" 2>/dev/null); then
		echo "wrote $OPENSCREEN_DIR/$OUT_DIR/compile_commands.json"
	fi
fi

echo "reopen the C++ files; clangd diagnostics should clear."
